# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e0eb7c8148e29943ae3412cb04513c54245cf806ba8080f1df441b8b39c958c435660da9bd6416b6a81ce831a460ce3054299a828d5f6de3db648a5e95dd5067

test:
  secret_key_base: 8dbb9251a900f67d01c8b9f8989328cf5ca36e8d96077db83e3b9cf5ab4b2cb292a727775e7de532453d160aab6e678aa26932bb7d36c11dfabbf75e07b2c3b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
